export default {
    awakeGreen: '#4e9eab',
    awakeLightGreen: '#44cee4',
    background: '#f6f6f6',
    badgeGreen: '#55d497',
    badgePurple: '#a488ff',
    badgeOrange: '#ff8d39',
    badgeRed: '#ff3c3c',
    badgeYellow: '#fff600',
    black: 'black',
    blue: '#5c7bff',
    bpmRed: '#ff3c3c',
    bpmPink: '#ffb0b0',
    darkGray: '#6f6f6f',
    gray: '#bdbdbd',
    purple: '#927afa',
    statPurple: '#753ef3',
    statLightPurple: '#a488ff',
    statRed: '#ff3939',
    statYellow: '#ffd34c',
    white: 'white',
}